export const interestsList = [
	{ title: "🎮 Gaming", value: "Gaming" },
	{ title: "💃🏻 Dancing", value: "Dancing" },
	{ title: "🍃 Nature", value: "Nature" },
	{ title: "🎵 Music", value: "Music" },
	{ title: "🎬 Movie", value: "Movie" },
	{ title: "📸 Photography", value: "Photography" },
	{ title: "👗 Fashion", value: "Fashion" },
	{ title: "📚 Book", value: "Book" },
	{ title: "✍🏻 Writing", value: "Writing" },
	{ title: "⚽️ Football", value: "Football" },
	{ title: "💪 Gym & Fitness", value: "Fitness" },
	{ title: "🍔 Food & Drink", value: "Cuisine" },
	{ title: "🎨 Painting", value: "Painting" },
	{ title: "🙂 People", value: "People" },
	{ title: "🐼 Animals", value: "Animals" },
	{ title: "🌇 Travel & Places", value: "Travel" },
];
